### ISSUE TITLE
タスクトレイに表示する

### ISSUE THREAD

**Issue by t-yng** [t-yng/review-cat#106]
## 概要
アプリケーションをタスクトレイで表示するようにする。

## TODO
- アイコンをタスクトレイに表示
- アイコンクリックでウィンドウを表示する

**Comment by mojahige** [comment]
以前やりたいなと思った時に見つけた Qiita の記事貼っておきますね。

https://qiita.com/narikei/items/aaee2c7e7e1a5ae61015#%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%B8%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3%E3%81%AE%E8%A1%A8%E7%A4%BA

**Comment by t-yng** [comment]
タスクトレイ表示の実装に [menubar](https://github.com/maxogden/menubar) を利用

アイコンのクリック周りの制御やウィンドウの表示がラップされているので、色々と楽

**Comment by t-yng** [comment]
タスクトレイに表示するアイコンサイズは [Electron で Tray を使う（macOS, Windows） \- Qiita](https://qiita.com/hibara/items/4a3c26817e5449ebf722#%E8%A1%A8%E7%A4%BA%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3%E3%81%AE%E3%82%B5%E3%82%A4%E3%82%BA) を参照

Windowsなどは考慮していないので、Macの場合だけを考慮してアイコン画像を用意している

**Comment by t-yng** [comment]
ドックからアイコンを削除する実装を追加したら、タイミングによってはウィンドウが非表示になる事がある。
トレイアイコンをクリックすれば再び表示されるクリティカルな問題ではない。

アプリ起動後にすぐにトレイアイコンをクリックしてウィンドウを表示した時だけ問題が発生する
